
let saludo = "Hola mundo"; // string
    console.log(typeof saludo); 

let edad  = 26; 
    console.log(typeof edad);//number

let nombre = "Bruno"; 
    console.log(typeof nombre);//String

let mayor18 = true; 
    console.log(typeof mayor18); //boolean
 
let x;
    console.log(typeof x); //undefined

let bateria = "25";
    console.log(typeof bateria); //number

let tienesMascotas = "false";
    console.log(typeof tienesMascotas); //String

let promedio = 238.90;
    console.log(typeof promedio); //number
 
let nada = null;
    console.log(typeof nada); //null

let y;
    console.log(typeof y); //undefined 

